### ISSUE TITLE
PhysicalResourceId not set in response

### ISSUE THREAD

**Issue by Lewenhaupt** [udondan/aws-cloudformation-custom-resource#5]
Hi,

There is an issue with the body generated. The fallback when self.PhysicalResourceId is not set is incorrect.
`PhysicalResourceId: self.PhysicalResourceId || event.ResourceProperties.Name`
I believe it should be
`PhysicalResourceId: self.PhysicalResourceId || event.PhysicalResourceId`

**Comment by udondan** [comment]
Fixed via #6
